import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import ToastProvider from "@/providers/ToastProvider";
import Header from "@/components/Header";
import ClientOnly from "@/components/ClientOnly";
import AtomProvider from "@/providers/AtomProvider";
import getCurrentUser from "@/actions/getCurrentUser";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({children}: {children: React.ReactNode }) {
    const currentUser = await getCurrentUser()
    return (
        <html lang="en" className='bg-gray-900'>
        <body className={inter.className}>
        <AtomProvider>
            <ClientOnly>
                <ToastProvider/>
            </ClientOnly>
            <Header currentUser={currentUser}/>
            <main>
                {children}
            </main>
        </AtomProvider>
        </body>
        </html>
    )
}
